In [ ]:
#!pip install transformers datasets librosa torch protect accelerate evaluate seqeval

In [ ]:
#!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.24.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.7.0->evaluate) (0.24.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.7.0->evaluate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.7 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
import sys
sys.path.append('/content/drive/MyDrive/colab_packages')

### for importing evaluate

In [ ]:
import os
import gc
import json
import torch
import pandas as pd
import itertools
import evaluate
import numpy as np
from pathlib import Path
from datasets import load_from_disk
from transformers import (
    Wav2Vec2ForSequenceClassification,
    HubertForSequenceClassification,
    Trainer, TrainingArguments, Wav2Vec2Processor
)

In [ ]:
base_dir = Path("/content/drive/MyDrive/Colab022Notebooks/GP")
arrow_save_dir = base_dir / "Arrow_Datasets"
models_save_dir = base_dir / "Saved_Trained_Models"
results_dir = base_dir / "Master_Grid_Search_Results"

os.makedirs(models_save_dir, exist_ok=True)
os.makedirs(results_dir, exist_ok=True)

# Models & hyperparamters
models = ["facebook/wav2vec2-base", "facebook/hubert-base-ls960"]
learning_rates = [3e-5, 5e-5]
batch_sizes = [8, 16]

metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    predictions = np.argmax(eval_pred.predictions, axis=1)
    return metric.compute(predictions=predictions, references=eval_pred.label_ids)

# Data collator
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union
@dataclass
class DataCollatorForAudio:
    processor: Wav2Vec2Processor
    padding: Union[bool, str] = True
    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        input_features = [{"input_values": feature["input_values"]} for feature in features]
        label_features = [feature["label"] for feature in features]
        batch = self.processor.pad(input_features, padding=self.padding, return_tensors="pt")
        batch["labels"] = torch.tensor(label_features)
        return batch

dummy_processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base")
data_collator = DataCollatorForAudio(processor=dummy_processor)

master_results = pd.DataFrame(columns=['Dataset', 'Model', 'LR', 'Batch_Size', 'Accuracy', 'Loss', 'Model_Path'])
datasets_available = ["CREMA-D", "EYASE"]

In [ ]:

print("🚀 STARTING TRAINING PIPELINE...")

for dataset_name in datasets_available:
    dataset_path = arrow_save_dir / dataset_name
    label_path = arrow_save_dir / f"{dataset_name}_labels.json"

    if not dataset_path.exists():
        continue

    print(f"\n{'='*50}\n📂 LOADING ARROW DATASET: {dataset_name}\n{'='*50}")

    # fetch Data
    encoded_dataset = load_from_disk(str(dataset_path))
    encoded_train = encoded_dataset["train"]
    encoded_test = encoded_dataset["test"]

    # 2. fetch labels
    with open(label_path, "r") as f:
        label2id = json.load(f)
    id2label = {int(v): k for k, v in label2id.items()}
    num_labels = len(label2id)

    combinations = list(itertools.product(models, learning_rates, batch_sizes))

    for model_checkpoint, lr, bs in combinations:
        clean_model_name = model_checkpoint.split('/')[-1]
        exp_name = f"{dataset_name}_{clean_model_name}_LR{lr}_BS{bs}"
        final_model_path = models_save_dir / exp_name

        print(f"\n🔥 Training: {exp_name}")

        torch.cuda.empty_cache()
        gc.collect()

        if "hubert" in model_checkpoint:
            model = HubertForSequenceClassification.from_pretrained(model_checkpoint, num_labels=num_labels, label2id=label2id, id2label=id2label)
        else:
            model = Wav2Vec2ForSequenceClassification.from_pretrained(model_checkpoint, num_labels=num_labels, label2id=label2id, id2label=id2label)

        model.freeze_feature_encoder()

        training_args = TrainingArguments(
            output_dir=f"{str(base_dir/"ModelExp")}_{exp_name}",
            eval_strategy="epoch",
            save_strategy="epoch",            # save every Epoch
            load_best_model_at_end=True,      # return best Epoch
            metric_for_best_model="accuracy",
            learning_rate=lr,
            per_device_train_batch_size=bs,
            per_device_eval_batch_size=bs,
            num_train_epochs=3,
            weight_decay=0.01,
            fp16=True,
            save_total_limit=1,
            remove_unused_columns=False
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=encoded_train,
            eval_dataset=encoded_test,
            data_collator=data_collator,
            compute_metrics=compute_metrics,
        )

        trainer.train()
        eval_result = trainer.evaluate()

        # save models
        trainer.save_model(str(final_model_path))
        print(f"💾 Model Saved to: {final_model_path}")

        new_row = {
            'Dataset': dataset_name,
            'Model': clean_model_name,
            'LR': lr,
            'Batch_Size': bs,
            'Accuracy': eval_result['eval_accuracy'],
            'Loss': eval_result['eval_loss'],
            'Model_Path': str(final_model_path)
        }
        master_results = pd.concat([master_results, pd.DataFrame([new_row])], ignore_index=True)
        master_results.to_csv(results_dir / "final_grid_search_report.csv", index=False)

print("\n🎉 ALL PIPELINES EXECUTED FLAWLESSLY! 🎉")

🚀 STARTING TRAINING PIPELINE...

==================================================
📂 LOADING ARROW DATASET: CREMA-D
==================================================

🔥 Training: CREMA-D_wav2vec2-base_LR3e-05_BS8

pytorch_model.bin:   0%|          | 0.00/380M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/380M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/CREMA-D_wav2vec2-base_LR3e-05_BS8

🔥 Training: CREMA-D_wav2vec2-base_LR3e-05_BS16

/tmp/ipython-input-1824645861.py:83: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  master_results = pd.concat([master_results, pd.DataFrame([new_row])], ignore_index=True)

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/CREMA-D_wav2vec2-base_LR3e-05_BS16

🔥 Training: CREMA-D_wav2vec2-base_LR5e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/CREMA-D_wav2vec2-base_LR5e-05_BS8

🔥 Training: CREMA-D_wav2vec2-base_LR5e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/CREMA-D_wav2vec2-base_LR5e-05_BS16

🔥 Training: CREMA-D_hubert-base-ls960_LR3e-05_BS8

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/378M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/CREMA-D_hubert-base-ls960_LR3e-05_BS8

🔥 Training: CREMA-D_hubert-base-ls960_LR3e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/CREMA-D_hubert-base-ls960_LR3e-05_BS16

🔥 Training: CREMA-D_hubert-base-ls960_LR5e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/CREMA-D_hubert-base-ls960_LR5e-05_BS8

🔥 Training: CREMA-D_hubert-base-ls960_LR5e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/CREMA-D_hubert-base-ls960_LR5e-05_BS16

==================================================
📂 LOADING ARROW DATASET: EYASE
==================================================

🔥 Training: EYASE_wav2vec2-base_LR3e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/EYASE_wav2vec2-base_LR3e-05_BS8

🔥 Training: EYASE_wav2vec2-base_LR3e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/EYASE_wav2vec2-base_LR3e-05_BS16

🔥 Training: EYASE_wav2vec2-base_LR5e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/EYASE_wav2vec2-base_LR5e-05_BS8

🔥 Training: EYASE_wav2vec2-base_LR5e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/EYASE_wav2vec2-base_LR5e-05_BS16

🔥 Training: EYASE_hubert-base-ls960_LR3e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/EYASE_hubert-base-ls960_LR3e-05_BS8

🔥 Training: EYASE_hubert-base-ls960_LR3e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/EYASE_hubert-base-ls960_LR3e-05_BS16

🔥 Training: EYASE_hubert-base-ls960_LR5e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/EYASE_hubert-base-ls960_LR5e-05_BS8

🔥 Training: EYASE_hubert-base-ls960_LR5e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/EYASE_hubert-base-ls960_LR5e-05_BS16

==================================================
📂 LOADING ARROW DATASET: TESS
==================================================

🔥 Training: TESS_wav2vec2-base_LR3e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/TESS_wav2vec2-base_LR3e-05_BS8

🔥 Training: TESS_wav2vec2-base_LR3e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/TESS_wav2vec2-base_LR3e-05_BS16

🔥 Training: TESS_wav2vec2-base_LR5e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/TESS_wav2vec2-base_LR5e-05_BS8

🔥 Training: TESS_wav2vec2-base_LR5e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.bias   | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
classifier.bias              | MISSING    |
classifier.weight            | MISSING    |
projector.weight             | MISSING    |
projector.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/TESS_wav2vec2-base_LR5e-05_BS16

🔥 Training: TESS_hubert-base-ls960_LR3e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |
projector.weight  | MISSING |
projector.bias    | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

##**Resuming Strategy**

In [ ]:
import os
import gc
import json
import torch
import pandas as pd
import itertools
import evaluate
import numpy as np
from pathlib import Path
from datasets import load_from_disk
from transformers import (
    Wav2Vec2ForSequenceClassification,
    HubertForSequenceClassification,
    Trainer, TrainingArguments, Wav2Vec2Processor
)

# ==========================================
# 1. paths
# ==========================================
out_dir = Path("/content/drive/MyDrive/Colab022Notebooks/GP")
arrow_save_dir = out_dir / "Arrow_Datasets"
models_save_dir = out_dir / "Saved_Trained_Models"
results_dir = out_dir / "Master_Grid_Search_Results"

os.makedirs(models_save_dir, exist_ok=True)
os.makedirs(results_dir, exist_ok=True)

# ==========================================
# 2. (The Resume Logic)
# ==========================================
csv_path = results_dir / "final_grid_search_report.csv"

# if csv paht exists , read and continue
if csv_path.exists():
    print("📥 Loading existing Grid Search Report to resume...")
    master_results = pd.read_csv(csv_path)
else:
    print("🆕 Creating new Grid Search Report...")
    master_results = pd.DataFrame(columns=['Dataset', 'Model', 'LR', 'Batch_Size', 'Accuracy', 'Loss', 'Model_Path'])

models = ["facebook/wav2vec2-base", "facebook/hubert-base-ls960"]
learning_rates = [3e-5, 5e-5]
batch_sizes = [8, 16]

metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    predictions = np.argmax(eval_pred.predictions, axis=1)
    return metric.compute(predictions=predictions, references=eval_pred.label_ids)

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union
@dataclass
class DataCollatorForAudio:
    processor: Wav2Vec2Processor
    padding: Union[bool, str] = True
    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        input_features = [{"input_values": feature["input_values"]} for feature in features]
        label_features = [feature["label"] for feature in features]
        batch = self.processor.pad(input_features, padding=self.padding, return_tensors="pt")
        batch["labels"] = torch.tensor(label_features)
        return batch

dummy_processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base")
data_collator = DataCollatorForAudio(processor=dummy_processor)

datasets_available = ["CREMA-D", "EYASE", "TESS", "BAVED"]

print("🚀 STARTING RESUME PIPELINE...")

# ==========================================
# 3. Smart retrain
# ==========================================
for dataset_name in datasets_available:
    dataset_path = arrow_save_dir / dataset_name
    label_path = arrow_save_dir / f"{dataset_name}_labels.json"

    if not dataset_path.exists():
        print(f"⚠️ Warning: Dataset {dataset_name} not found. Skipping...")
        continue

    print(f"\n{'='*50}\n📂 DATASET: {dataset_name}\n{'='*50}")

    encoded_dataset = load_from_disk(str(dataset_path))
    encoded_train = encoded_dataset["train"]
    encoded_test = encoded_dataset["test"]

    with open(label_path, "r") as f:
        label2id = json.load(f)
    id2label = {int(v): k for k, v in label2id.items()}
    num_labels = len(label2id)

    combinations = list(itertools.product(models, learning_rates, batch_sizes))

    for model_checkpoint, lr, bs in combinations:
        clean_model_name = model_checkpoint.split('/')[-1]
        exp_name = f"{dataset_name}_{clean_model_name}_LR{lr}_BS{bs}"
        final_model_path = models_save_dir / exp_name

        # ----------------------------------------------------
        # if trained , skip
        # ----------------------------------------------------
        if final_model_path.exists():
            print(f"⏭️ SKIPPING: {exp_name} (Already Trained & Saved)")
            continue

        print(f"\n🔥 Training: {exp_name}")

        torch.cuda.empty_cache()
        gc.collect()

        if "hubert" in model_checkpoint:
            model = HubertForSequenceClassification.from_pretrained(model_checkpoint, num_labels=num_labels, label2id=label2id, id2label=id2label)
        else:
            model = Wav2Vec2ForSequenceClassification.from_pretrained(model_checkpoint, num_labels=num_labels, label2id=label2id, id2label=id2label)

        model.freeze_feature_encoder()

        temp_out_dir = out_dir / f"temp_{exp_name}"

        training_args = TrainingArguments(
            output_dir=str(temp_out_dir),
            eval_strategy="epoch",
            save_strategy="epoch",
            load_best_model_at_end=True,
            metric_for_best_model="accuracy",
            learning_rate=lr,
            per_device_train_batch_size=bs,
            per_device_eval_batch_size=bs,
            num_train_epochs=3,
            weight_decay=0.01,
            fp16=True,
            save_total_limit=1,
            remove_unused_columns=False
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=encoded_train,
            eval_dataset=encoded_test,
            data_collator=data_collator,
            compute_metrics=compute_metrics,
        )

        # search for checkpoint
        last_checkpoint = None
        if temp_out_dir.exists():
            checkpoints = [d for d in os.listdir(temp_out_dir) if d.startswith("checkpoint-")]
            if checkpoints:
                # select the recent checkpoint
                checkpoints.sort(key=lambda x: int(x.split('-')[1]))
                last_checkpoint = str(temp_out_dir / checkpoints[-1])
                print(f"🔄 Found checkpoint! Resuming from: {last_checkpoint}")

        # train
        trainer.train(resume_from_checkpoint=last_checkpoint if last_checkpoint else None)
        eval_result = trainer.evaluate()

        # save
        trainer.save_model(str(final_model_path))
        print(f"💾 Model Saved to: {final_model_path}")

        new_row = {
            'Dataset': dataset_name,
            'Model': clean_model_name,
            'LR': lr,
            'Batch_Size': bs,
            'Accuracy': eval_result['eval_accuracy'],
            'Loss': eval_result['eval_loss'],
            'Model_Path': str(final_model_path)
        }

        new_df = pd.DataFrame([new_row])
        master_results = pd.concat([master_results, new_df], ignore_index=True)
        master_results.to_csv(csv_path, index=False)

print("\n🎉 ALL PIPELINES EXECUTED FLAWLESSLY! 🎉")

📥 Loading existing Grid Search Report to resume...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/159 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

🚀 STARTING RESUME PIPELINE...

==================================================
📂 DATASET: CREMA-D
==================================================
⏭️ SKIPPING: CREMA-D_wav2vec2-base_LR3e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: CREMA-D_wav2vec2-base_LR3e-05_BS16 (Already Trained & Saved)
⏭️ SKIPPING: CREMA-D_wav2vec2-base_LR5e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: CREMA-D_wav2vec2-base_LR5e-05_BS16 (Already Trained & Saved)
⏭️ SKIPPING: CREMA-D_hubert-base-ls960_LR3e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: CREMA-D_hubert-base-ls960_LR3e-05_BS16 (Already Trained & Saved)
⏭️ SKIPPING: CREMA-D_hubert-base-ls960_LR5e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: CREMA-D_hubert-base-ls960_LR5e-05_BS16 (Already Trained & Saved)

==================================================
📂 DATASET: EYASE
==================================================
⏭️ SKIPPING: EYASE_wav2vec2-base_LR3e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: EYASE_wav2vec2-base_LR3e-05_BS16 (Already Trained & Saved)
⏭️ SKIPPING: EYASE_wav2vec2-base_LR5e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: EYASE_wav2vec2-base_LR5e-05_BS16 (Already Trained & Saved)
⏭️ SKIPPING: EYASE_hubert-base-ls960_LR3e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: EYASE_hubert-base-ls960_LR3e-05_BS16 (Already Trained & Saved)
⏭️ SKIPPING: EYASE_hubert-base-ls960_LR5e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: EYASE_hubert-base-ls960_LR5e-05_BS16 (Already Trained & Saved)

==================================================
📂 DATASET: TESS
==================================================
⏭️ SKIPPING: TESS_wav2vec2-base_LR3e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: TESS_wav2vec2-base_LR3e-05_BS16 (Already Trained & Saved)
⏭️ SKIPPING: TESS_wav2vec2-base_LR5e-05_BS8 (Already Trained & Saved)
⏭️ SKIPPING: TESS_wav2vec2-base_LR5e-05_BS16 (Already Trained & Saved)

🔥 Training: TESS_hubert-base-ls960_LR3e-05_BS8

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/378M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
projector.weight  | MISSING |
classifier.bias   | MISSING |
projector.bias    | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/TESS_hubert-base-ls960_LR3e-05_BS8

🔥 Training: TESS_hubert-base-ls960_LR3e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
projector.weight  | MISSING |
classifier.bias   | MISSING |
projector.bias    | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/TESS_hubert-base-ls960_LR3e-05_BS16

🔥 Training: TESS_hubert-base-ls960_LR5e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
projector.weight  | MISSING |
classifier.bias   | MISSING |
projector.bias    | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/TESS_hubert-base-ls960_LR5e-05_BS8

🔥 Training: TESS_hubert-base-ls960_LR5e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
projector.weight  | MISSING |
classifier.bias   | MISSING |
projector.bias    | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/TESS_hubert-base-ls960_LR5e-05_BS16

==================================================
📂 DATASET: BAVED
==================================================

🔥 Training: BAVED_wav2vec2-base_LR3e-05_BS8

pytorch_model.bin:   0%|          | 0.00/380M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.weight_proj.bias   | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
projector.weight             | MISSING    |
classifier.bias              | MISSING    |
projector.bias               | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/380M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/BAVED_wav2vec2-base_LR3e-05_BS8

🔥 Training: BAVED_wav2vec2-base_LR3e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.weight_proj.bias   | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
projector.weight             | MISSING    |
classifier.bias              | MISSING    |
projector.bias               | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/BAVED_wav2vec2-base_LR3e-05_BS16

🔥 Training: BAVED_wav2vec2-base_LR5e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.weight_proj.bias   | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
projector.weight             | MISSING    |
classifier.bias              | MISSING    |
projector.bias               | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/BAVED_wav2vec2-base_LR5e-05_BS8

🔥 Training: BAVED_wav2vec2-base_LR5e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2ForSequenceClassification LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |
-----------------------------+------------+-
quantizer.weight_proj.bias   | UNEXPECTED |
project_q.weight             | UNEXPECTED |
project_q.bias               | UNEXPECTED |
project_hid.bias             | UNEXPECTED |
quantizer.weight_proj.weight | UNEXPECTED |
quantizer.codevectors        | UNEXPECTED |
project_hid.weight           | UNEXPECTED |
projector.weight             | MISSING    |
classifier.bias              | MISSING    |
projector.bias               | MISSING    |
classifier.weight            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/BAVED_wav2vec2-base_LR5e-05_BS16

🔥 Training: BAVED_hubert-base-ls960_LR3e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
projector.weight  | MISSING |
classifier.bias   | MISSING |
projector.bias    | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/BAVED_hubert-base-ls960_LR3e-05_BS8

🔥 Training: BAVED_hubert-base-ls960_LR3e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
projector.weight  | MISSING |
classifier.bias   | MISSING |
projector.bias    | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/BAVED_hubert-base-ls960_LR3e-05_BS16

🔥 Training: BAVED_hubert-base-ls960_LR5e-05_BS8

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
projector.weight  | MISSING |
classifier.bias   | MISSING |
projector.bias    | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/BAVED_hubert-base-ls960_LR5e-05_BS8

🔥 Training: BAVED_hubert-base-ls960_LR5e-05_BS16

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

HubertForSequenceClassification LOAD REPORT from: facebook/hubert-base-ls960
Key               | Status  |
------------------+---------+-
projector.weight  | MISSING |
classifier.bias   | MISSING |
projector.bias    | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

💾 Model Saved to: /content/drive/MyDrive/Colab022Notebooks/GP/Saved_Trained_Models/BAVED_hubert-base-ls960_LR5e-05_BS16

🎉 ALL PIPELINES EXECUTED FLAWLESSLY! 🎉